[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_USE_URL = "deployed"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_USE_URL = "deployed"